---
apiVersion: v1
kind: Pod
metadata:
  name: x-wing
spec:
  containers:
    - name: x-wing
      image: mattslater.io/star-wars:0.1.0
      env:
        - name: ROLE
          value: xwing
        - name: COMMANDER
          value: matt
        - name: TARGET
          value: death-star.death-star.svc.cluster.local
        - name: PORT
          value: "8080"
